# .concatenate()

In [1]:
import numpy as np

In [5]:
jk = np.array([1,2,3,4,5,6,7])
sj = np.array([8,9,10,11,12,13,14])
np.concatenate((jk,sj))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
jk = np.arange(1,21).reshape(4,5)
jk

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
sj = np.arange(21,31).reshape(2,5)
sj

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
np.concatenate((jk,sj))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

###### **note: in the above 2D example, no. of columns must match to concatenate. No. of rows doesnt matter.

In [23]:
jk = np.arange(1,28).reshape(3,3,3)
jk

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [28]:
sj = np.arange(1,10).reshape(1,3,3)
sj

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [29]:
np.concatenate((jk,sj))


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

##### Can cancatenate 3D array as well.

In [34]:
np.concatenate((jk,sj),axis = 0)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]])

In [35]:
np.concatenate((jk,sj),axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

##### to concatenate horizontally (axis = 1), the no. of rows must be of equal size. refer below example

In [36]:
jk = np.arange(1,19).reshape(2,3,3)
jk

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [41]:
sj = np.arange(19,37).reshape(2,3,3)
sj

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [42]:
np.concatenate((jk,sj), axis = 1)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [43]:
np.concatenate((jk,sj))

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

##### concluding that we can concatenate 1d,2d or any multidimensional array if axis are equal.