# Boolean operators/operations:
##### Boolean operators returns boolean value which we can use for filteration.

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

##### So, here we filtered above operation

In [6]:
a[a>5]

array([6, 7, 8, 9])

##### another example:

In [7]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False])

##### return values which are even

In [12]:
a [a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##### return values which are odd:

In [15]:
a[~(a%2==0)]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

##### using more boolean operators: like 'or' = '|'

In [19]:
a[(a<5)|(a>16)]

array([ 0,  1,  2,  3,  4, 17, 18, 19])

##### using boolean operator : 'and' = ' '&'

In [20]:
a[(a<5) & (a<3)]

array([0, 1, 2])