# .linspace():
##### use np.linspace() to create an array with values that are spaced linearly in a specified interval. In simple language, to create an evenly spaced sequence in a specified interval.

In [2]:
import numpy as np

In [4]:
a = np.linspace(1,10, num=5)
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# .arange():
##### to create an array with range of elements.

In [7]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = np.arange(100,151, step=5)

a

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150])

# .empty():
##### np.empty() creates an array with random elements.

In [27]:
a = np.empty(1)
a

array([10.])

In [28]:
a = np.empty(10)
a

array([6.79038654e-313, 6.79038653e-313, 2.37663529e-312, 2.14321575e-312,
       2.37663529e-312, 2.56761491e-312, 1.12465777e-312, 2.12199579e-313,
       8.45596649e-307, 1.69121367e-306])

# .ones():
##### returns a new array of given shape and data type, where the elements's value is set to 1. Similar to .zeros()

In [3]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [19]:
a = np.ones([4,2,5])
a

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

# .zeros()
##### returns an array with zeros.

In [20]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
a = np.zeros([2,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
a = np.zeros([4,3,5])
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

# Indexing & Slicing:


##### Single dimension:

In [25]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a[3],a[5],a[-1]

(4, 6, 9)

##### passing another list containing the indexes value; (example below)

In [28]:
a[[1,3,-2]]

array([2, 4, 8])

In [29]:
a[0:4]

array([1, 2, 3, 4])

##### 2D array:

In [33]:
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

##### pass the index value in form == (Row, Column)

##### fetching values 3,4,8,9:

In [34]:
a[:,2:4]

array([[3, 4],
       [8, 9]])

##### fetching only 2nd row:

In [35]:
a[1:2,:]

array([[ 6,  7,  8,  9, 10]])

##### fetching only last column i.e, 5,10:

In [36]:
a[:,4:5]

array([[ 5],
       [10]])

##### 3D array

In [69]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [72]:
a[1,1:2,:]

array([[13, 14, 15]])

In [73]:
a=np.arange(1,10).reshape(3,1,3)
a

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [74]:
a[2,:,:]

array([[7, 8, 9]])

In [75]:
a[1,:,1:]

array([[5, 6]])

In [76]:
a[1:,:,:]

array([[[4, 5, 6]],

       [[7, 8, 9]]])

# .dtype
##### returns the data type

In [77]:
a.dtype

dtype('int32')

# .ndim
##### returns number of dimension

In [78]:
a.ndim

3

# .shape
##### returns the shape of an multi dimension array

In [79]:
a.shape

(3, 1, 3)

# .size
##### returns the number of element in an array

In [80]:
a.size

9